name: auth-adt
version: 0.1.0
synopsis: Authenticated Data Structures Generically
description: Authenticated Data Structures Generically
maintainer: Adjoint Inc (info@adjoint.io)
license: Apache
github: adjoint-io/auth-adt
category: Cryptography

extra-source-files:
- README.md

dependencies:
  # Prelude
  - base >= 4.7 && < 5
  - protolude  >= 0.2
  - cryptonite
  - bytestring
  - random
  - memory
  - merkle-tree 

library:
  source-dirs: src

  ghc-options:
    -fwarn-tabs
    -fwarn-incomplete-patterns
    -fwarn-incomplete-record-updates
    -fwarn-redundant-constraints
    -fwarn-implicit-prelude
    -fwarn-overflowed-literals
    -fwarn-orphans
    -fwarn-identities
    -fwarn-dodgy-exports
    -fwarn-dodgy-imports
    -fwarn-duplicate-exports
    -fwarn-overlapping-patterns
    -fwarn-missing-fields
    -fwarn-missing-methods
    -fwarn-missing-signatures
    -fwarn-noncanonical-monad-instances
    -fwarn-unused-pattern-binds
    -fwarn-unused-type-patterns
    -fwarn-unrecognised-pragmas
    -fwarn-wrong-do-bind
    -fno-warn-name-shadowing
    -fno-warn-unused-binds
    -fno-warn-unused-matches
    -fno-warn-unused-do-bind

  default-extensions:
    - LambdaCase
    - RecordWildCards
    - OverloadedStrings
    - NoImplicitPrelude
    - FlexibleInstances

  exposed-modules:
    - Auth
